# ==============================================================================
# Merged Lakeflow Source: apis
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from __future__ import annotations
from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import logging
import math
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/apis/apis_schemas.py
    ########################################################

    SUPPORTED_TABLES: tuple[str, ...] = ("items", "values", "timeseries")

    # ---------------------------------------------------------------------------
    # Shared struct shapes
    # ---------------------------------------------------------------------------

    #: INFERRED. One entry per numeric ``attrib`` ID the caller asked for. The
    #: spec documents neither the field names nor the ID-to-meaning registry, so
    #: both sides are kept as open strings.
    ITEM_ATTRIBUTE_STRUCT = StructType(
        [
            StructField("attrib_id", StringType(), True),
            StructField("value", StringType(), True),
        ]
    )

    # ---------------------------------------------------------------------------
    # Table schemas
    # ---------------------------------------------------------------------------

    #: INFERRED, except where noted (see LIVE VALIDATION FINDINGS above).
    #:
    #: ``instance`` is not part of any response body — it is the ``{instance}``
    #: path segment, stamped onto every row because item names are only unique
    #: within a Hive instance.
    #:
    #: ``module`` is derived client-side by splitting ``item_name`` on the first
    #: ``.``. CONFIRMED by a live spot-check: the derived value matches the
    #: real ``modules`` endpoint's module names exactly, including for deeply
    #: nested item paths.
    #:
    #: ``item_type`` is CONFIRMED live (observed values: ``"Signal"``,
    #: ``"Function item"``, ``"Status"``) — the source's own field is literally
    #: named ``"type"``, renamed here to avoid colliding with Python/SQL
    #: connotations of a bare ``type`` column.
    ITEMS_SCHEMA = StructType(
        [
            StructField("instance", StringType(), True),
            StructField("item_name", StringType(), True),
            StructField("module", StringType(), True),
            StructField("item_type", StringType(), True),
            StructField("attributes", ArrayType(ITEM_ATTRIBUTE_STRUCT, True), True),
        ]
    )

    #: SPEC-DECLARED (``single_value_t``) plus the ``instance`` scoping column.
    #: The declared ``value: {v, q, t}`` triple is flattened onto three
    #: top-level columns rather than kept as a nested struct, so downstream SQL
    #: can reference ``value``/``quality``/``timestamp`` directly.
    #:
    #: ``value`` is typed as ``StringType`` because the spec gives it the
    #: *empty* schema ``{}``: no type constraint whatsoever. The underlying
    #: historian point may be numeric, boolean or textual and only the source
    #: system knows which. String is the lossless-enough common denominator;
    #: the framework's ``parse_value`` stringifies whatever JSON scalar arrives,
    #: so a numeric point lands as e.g. ``"42.7"`` rather than failing the
    #: batch. Downstream casts should be applied in SQL where the point's real
    #: type is known.
    #:
    #: ``quality`` is an open string on purpose: the ``quality`` *query*
    #: parameter is constrained to ``good``/``uncertain``/``bad``, but the
    #: response field carries no such enum, so richer raw quality codes (e.g.
    #: OPC codes) must not be rejected.
    #:
    #: ``timestamp`` is NOT ISO-8601, confirmed live: an observed value was
    #: ``"2026-09-22 20:38:02.545"`` — space-separated (no ``T``), millisecond
    #: precision, no timezone suffix. Kept as a string regardless, since the
    #: response field declares no format and a different Hive deployment could
    #: render it differently. It also doubles as the table's cursor field (see
    #: ``TABLE_METADATA`` below); this is safe because the connector's own
    #: cursor/offset values are always self-generated ISO-8601 strings, never
    #: parsed out of a response ``t`` value. Downstream consumers casting this
    #: column should use its real format, e.g.
    #: ``TO_TIMESTAMP(timestamp, 'yyyy-MM-dd HH:mm:ss.SSS')``, not
    #: ``TO_TIMESTAMP(timestamp)``.
    VALUES_SCHEMA = StructType(
        [
            StructField("instance", StringType(), True),
            StructField("item_name", StringType(), True),
            StructField("value", StringType(), True),
            StructField("quality", StringType(), True),
            StructField("timestamp", StringType(), True),
        ]
    )

    #: INFERRED. One row per (item, point in time). Structurally identical to
    #: ``values`` (same flattened ``value``/``quality``/``timestamp`` columns)
    #: because the spec's only per-item value shape is ``single_value_t``, and
    #: ``aggregate``/``interval`` produce one such triple per resample bucket.
    TIMESERIES_SCHEMA = StructType(
        [
            StructField("instance", StringType(), True),
            StructField("item_name", StringType(), True),
            StructField("value", StringType(), True),
            StructField("quality", StringType(), True),
            StructField("timestamp", StringType(), True),
        ]
    )

    TABLE_SCHEMAS: dict[str, StructType] = {
        "items": ITEMS_SCHEMA,
        "values": VALUES_SCHEMA,
        "timeseries": TIMESERIES_SCHEMA,
    }

    # ---------------------------------------------------------------------------
    # Table metadata
    # ---------------------------------------------------------------------------

    #: ``items``      — snapshot. No incremental parameter exists on
    #:                  ``GET /hive/{instance}/items`` (the ``item`` wildcard
    #:                  narrows scope, it is not a change cursor) and no
    #:                  created/modified field is declared, so the catalog is
    #:                  fully re-listed each run.
    #: ``values``     — cdc (upsert-only). ``updatedSince`` is a genuine
    #:                  incremental signal and the endpoint returns one row per
    #:                  item, so ``(instance, item_name)`` upserts cleanly.
    #:                  ``cdc_with_deletes`` is impossible: the spec has no
    #:                  tombstone field and no delete endpoint.
    #: ``timeseries`` — append. Recorded history is immutable and the endpoint is
    #:                  addressed by a required ``[starttime, endtime)`` window.
    #:
    #: Note on ``timeseries.primary_keys``: the *logical* uniqueness key is
    #: ``(instance, item_name, timestamp)``, but append-only tables are inserted
    #: rather than merged, so no primary key is declared. The connector keeps
    #: its time windows half-open and non-overlapping so inserts cannot
    #: duplicate across window boundaries.
    TABLE_METADATA: dict[str, dict] = {
        "items": {
            "primary_keys": ["instance", "item_name"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        "values": {
            "primary_keys": ["instance", "item_name"],
            "cursor_field": "timestamp",
            "ingestion_type": "cdc",
        },
        "timeseries": {
            "primary_keys": [],
            "cursor_field": "timestamp",
            "ingestion_type": "append",
        },
    }

    # ---------------------------------------------------------------------------
    # HTTP / retry constants
    # ---------------------------------------------------------------------------

    DEFAULT_REQUEST_TIMEOUT = 30
    DEFAULT_MAX_RETRIES = 4
    INITIAL_BACKOFF_SECONDS = 1.0
    RETRIABLE_STATUS_CODES = frozenset({429, 500, 502, 503, 504})

    #: ``Authorization`` is declared as a raw ``apiKey`` header, not an
    #: ``http``/``bearer`` scheme, so the spec never says whether the value is
    #: ``Bearer <token>`` or the bare token. We default to the conventional
    #: ``Bearer`` prefix and let operators blank it out via the ``auth_scheme``
    #: option if live testing shows otherwise.
    DEFAULT_AUTH_SCHEME = "Bearer"

    # ---------------------------------------------------------------------------
    # Read-shaping defaults
    # ---------------------------------------------------------------------------

    #: ``item`` is a *required* query parameter on items/values/timeseries, so
    #: there is no "no filter" call. ``*`` is the spec's own wildcard syntax and
    #: matches everything.
    DEFAULT_ITEM_PATTERN = "*"

    #: Format is always JSON — the spec defines no CSV schema.
    RESPONSE_FORMAT = "json"

    #: Timestamp rendering for ``updatedSince`` / ``starttime`` / ``endtime``.
    #: ``apis_datetime_format`` also accepts relative "OPC time" expressions
    #: (``DAY-1D``), but incremental reads must be deterministic and replayable,
    #: so the connector always computes and sends absolute ISO-8601 instants.
    #: Second precision with a ``Z`` suffix matches the spec's own example
    #: (``2023-06-01T12:00:00Z``).
    TIMESTAMP_FORMAT = "%Y-%m-%dT%H:%M:%SZ"
    EPOCH_ISO = "1970-01-01T00:00:00Z"

    #: Size of one ``timeseries`` partition, in seconds.
    DEFAULT_WINDOW_SECONDS = 86_400

    #: Upper bound on partitions handed to Spark for a single micro-batch. If the
    #: requested range needs more windows than this, the window is grown instead
    #: of emitting thousands of tiny tasks.
    DEFAULT_MAX_PARTITIONS = 64

    #: How far back a first ``timeseries`` run reaches when the caller supplies
    #: neither a checkpoint nor ``start_timestamp``. Three years is deliberately
    #: generous — a historian backfill is usually the point of the first run —
    #: but it is bounded, and operators who want a short first run set
    #: ``start_timestamp`` or lower ``backfill_days``.
    DEFAULT_BACKFILL_DAYS = 1095

    #: Admission control for the single-driver ``read_table`` path.
    DEFAULT_MAX_RECORDS_PER_BATCH = 1000

    #: Cap on how many windows one ``read_table`` call will walk before handing
    #: a micro-batch back to the framework, so the driver path advances in
    #: comparable strides to the partitioned path.
    DEFAULT_MAX_WINDOWS_PER_READ = 64

    #: ``quality`` filter enum, per the spec, for ``values`` and ``timeseries``.
    QUALITY_VALUES = frozenset({"good", "uncertain", "bad"})

    #: ``interval`` bounds for ``timeseries``, per the spec.
    MIN_INTERVAL_SECONDS = 1
    MAX_INTERVAL_SECONDS = 86_400

    #: The full ``aggregate`` enum, verbatim from the spec. Validated locally so
    #: a typo fails fast with a useful message instead of a bare HTTP 400.
    AGGREGATE_VALUES = frozenset(
        {
            "interpolative",
            "total",
            "average",
            "timeaverage",
            "count",
            "regstddev",
            "minimumactualtime",
            "minimum",
            "maximumactualtime",
            "maximum",
            "start",
            "end",
            "delta",
            "regslope",
            "regconst",
            "regdev",
            "variance",
            "range",
            "duration_good",
            "duration_bad",
            "percent_good",
            "percent_bad",
            "worst_quality",
            "annotation_count",
            "sum",
            "interpolative_0",
            "median",
            "ua_minimumactualtime2",
            "ua_maximumactualtime2",
            "ua_range2",
            "vec_sum",
            "vec_aver",
            "vec_min",
            "vec_max",
            "displayvalues",
            "lowpassfilter",
            "movingaveragebycount",
            "movingaveragebytime",
            "ua_percentgood",
            "ua_percentbad",
        }
    )


    ########################################################
    # src/databricks/labs/community_connector/sources/apis/apis.py
    ########################################################

    logger = logging.getLogger(__name__)

    _INSTANCE_NAME_KEYS = ("name", "instance", "instance_name", "hive", "hive_instance", "id")
    _ITEM_NAME_KEYS = ("item_name", "name", "item", "itemname", "tag")
    _POINT_KEYS = ("v", "q", "t")


    class ApisLakeflowConnect(LakeflowConnect, SupportsPartitionedStream):
        """LakeflowConnect implementation for the Apis REST Service.

        Connection options
        ------------------
        base_url
            Root URL of the Apis REST Service, e.g. ``http://hive-host:8080``.
            Required. The spec's ``http://localhost:8080`` server entry is a
            dev placeholder and is never assumed here.
        token
            Pre-issued bearer token sent in the ``Authorization`` header.
            Required. Aliases: ``api_token``, ``access_token``, ``bearer_token``.
            The spec defines no OAuth2 flow, no token endpoint and no scopes, so
            the credential is treated as static.
        auth_scheme
            Prefix for the ``Authorization`` header value. Defaults to
            ``Bearer``. Set to an empty string (or ``none``/``raw``) to send the
            bare token — the spec models the header as a raw ``apiKey`` and does
            not state which form the server wants.
        instance / instances
            Optional. Comma-separated Hive instance name(s). When omitted the
            connector resolves them once via ``GET /hive``.
        request_timeout
            Per-request timeout in seconds (default 30).
        max_retries
            Attempts per request before giving up (default 4).
        verify_ssl
            ``false`` to skip TLS verification — on-prem Hive deployments often
            use a self-signed certificate.

        Table options (per table; never put these in the connection options)
        --------------------------------------------------------------------
        instance / instances
            Overrides the connection-level instance selection for one table.
        item / items / item_patterns
            Comma-separated ``item`` wildcard patterns, e.g.
            ``Work*.Sig*,Logger.*``. Defaults to ``*``. Each pattern becomes its
            own partition, which is also how response truncation (``206``) is
            kept at bay, since the source offers no continuation mechanism.
        attrib
            ``items`` only. Comma-separated numeric attribute IDs to request.
        quality
            ``values``/``timeseries`` only. One of ``good``/``uncertain``/``bad``
            — a *minimum* quality filter.
        aggregate, interval
            ``timeseries`` only. Server-side aggregation function and resample
            interval in seconds (1..86400).
        start_timestamp
            ``timeseries`` only. ISO-8601 lower bound for the first run. Strongly
            recommended: without it the first run reaches back
            ``backfill_days``.
        backfill_days
            ``timeseries`` only. First-run lookback when ``start_timestamp`` is
            absent (default 1095).
        window_seconds
            ``timeseries`` only. Partition width in seconds (default 86400).
            Start small when testing.
        max_partitions
            Upper bound on partitions per micro-batch (default 64). When the
            range needs more windows than this, windows are widened rather than
            emitting thousands of tasks.
        max_records_per_batch
            Admission control for the single-driver ``read_table`` path
            (default 1000).
        max_windows_per_read
            ``timeseries`` only. Windows one ``read_table`` call may walk before
            returning a micro-batch (default 64).
        """

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)

            base_url = options.get("base_url") or options.get("host") or options.get("url")
            if not base_url:
                raise ValueError(
                    "Apis connector requires connection option 'base_url', e.g. "
                    "'http://hive-host:8080'"
                )
            self._base_url = str(base_url).rstrip("/")

            token = (
                options.get("token")
                or options.get("api_token")
                or options.get("access_token")
                or options.get("bearer_token")
            )
            if not token:
                raise ValueError(
                    "Apis connector requires connection option 'token' (aliases: "
                    "'api_token', 'access_token', 'bearer_token') — a pre-issued "
                    "bearer token for the Authorization header"
                )
            self._token = str(token)

            scheme = options.get("auth_scheme", DEFAULT_AUTH_SCHEME)
            if scheme is None or str(scheme).strip().lower() in ("", "none", "raw"):
                self._auth_scheme = ""
            else:
                self._auth_scheme = str(scheme).strip()

            self._timeout = _parse_int(
                options.get("request_timeout"), DEFAULT_REQUEST_TIMEOUT, minimum=1
            )
            self._max_retries = _parse_int(
                options.get("max_retries"), DEFAULT_MAX_RETRIES, minimum=1
            )
            self._verify_ssl = str(options.get("verify_ssl", "true")).strip().lower() not in (
                "false",
                "0",
                "no",
            )

            #: Instances pinned at the connection level, if any.
            self._configured_instances = _split_csv(
                options.get("instance") or options.get("instances")
            )
            #: Cache for ``GET /hive`` discovery. Driver-side only; partition
            #: descriptors carry the resolved instance so executors never call
            #: ``/hive``.
            self._discovered_instances: list[str] | None = None

            # Cap every offset this connector returns at construction time.
            # Trigger.AvailableNow stops only when latest_offset repeats itself,
            # so a cursor that chases a live historian's incoming data would
            # never let a trigger finish. The next trigger builds a fresh
            # instance with a newer _init_time and picks up the remainder.
            self._init_time = _format_iso(datetime.now(timezone.utc))

        # ------------------------------------------------------------------
        # Session — created lazily and never pickled to executors
        # ------------------------------------------------------------------

        @property
        def _session(self) -> requests.Session:
            session = getattr(self, "_session_obj", None)
            if session is None:
                session = requests.Session()
                self._session_obj = session
            return session

        def __getstate__(self) -> dict:
            # Spark ships this object to executors; a live Session (sockets,
            # connection pool) must not travel with it. read_partition rebuilds
            # one lazily on the worker from self.options-derived state.
            state = dict(self.__dict__)
            state.pop("_session_obj", None)
            return state

        # ------------------------------------------------------------------
        # LakeflowConnect — discovery
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            """Static list — the source has no schema/discovery meta-API.

            ``/hive`` only enumerates instances (a path parameter), not tables,
            and ``runstate``/``modules`` are instance-level lookups rather than
            row-producing objects.
            """
            return list(SUPPORTED_TABLES)

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        # ------------------------------------------------------------------
        # SupportsPartitionedStream
        # ------------------------------------------------------------------

        def is_partitioned(self, table_name: str) -> bool:
            """All three tables fan out cleanly, so all three are partitioned.

            ``items``/``values`` partition on ``(instance x item pattern)``;
            ``timeseries`` adds the time window as a third dimension.
            """
            return table_name in SUPPORTED_TABLES

        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the high-water mark, capped at construction time.

            Metadata-only: no records are fetched here. The source exposes no
            "max timestamp" endpoint at all — there is nothing cheap to query —
            so the cap *is* the high-water mark. Returning the constant
            ``_init_time`` makes ``Trigger.AvailableNow`` converge on the second
            call for every table, which is the required termination condition.
            """
            self._validate_table(table_name)
            return {"cursor": self._init_time}

        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Split the read into self-contained descriptors.

            Batch (both offsets ``None``) covers the whole table. Streaming
            covers ``(start_offset, end_offset]`` and returns ``[]`` once the two
            are equal, which is how the micro-batch loop stops.
            """
            self._validate_table(table_name)
            table_options = table_options or {}

            # Streaming steady state: nothing new since the last commit.
            if (
                start_offset is not None
                and end_offset is not None
                and start_offset == end_offset
            ):
                return []

            instances = self._resolve_instances(table_options)
            patterns = _resolve_item_patterns(table_options)

            if table_name == "items":
                # Snapshot: every partition is a full re-list of one
                # (instance, pattern) slice. No cursor is involved.
                return [
                    {"instance": inst, "item": pattern}
                    for inst in instances
                    for pattern in patterns
                ]

            if table_name == "values":
                # CDC: updatedSince is the only incremental knob the endpoint
                # has — there is no matching "updatedUntil", so a partition is
                # simply "current values for this slice, changed since X".
                updated_since = (start_offset or {}).get("cursor")
                partitions: list[dict] = []
                for inst in instances:
                    for pattern in patterns:
                        descriptor = {"instance": inst, "item": pattern}
                        if updated_since:
                            descriptor["updated_since"] = updated_since
                        partitions.append(descriptor)
                return partitions

            # timeseries — the range-query table, and the reason this connector
            # is partitioned at all.
            start_iso, end_iso = self._resolve_timeseries_range(
                table_options, start_offset, end_offset
            )
            if start_iso >= end_iso:
                return []

            slices = max(1, len(instances) * len(patterns))
            windows = self._build_windows(start_iso, end_iso, table_options, slices)
            return [
                {
                    "instance": inst,
                    "item": pattern,
                    "starttime": window_start,
                    "endtime": window_end,
                }
                for inst in instances
                for pattern in patterns
                for window_start, window_end in windows
            ]

        def read_partition(
            self,
            table_name: str,
            partition: dict,
            table_options: dict[str, str],
        ) -> Iterator[dict]:
            """Read one partition. Runs on an executor; must be self-contained.

            Everything needed is in ``partition`` plus ``self.options`` — in
            particular the ``{instance}`` path segment is baked into the
            descriptor so no worker ever calls ``GET /hive``.
            """
            self._validate_table(table_name)
            table_options = table_options or {}
            instance = partition["instance"]
            pattern = partition.get("item", DEFAULT_ITEM_PATTERN)

            if table_name == "items":
                yield from self._fetch_items(instance, [pattern], table_options)
            elif table_name == "values":
                yield from self._fetch_values(
                    instance, [pattern], table_options, partition.get("updated_since")
                )
            else:
                yield from self._fetch_timeseries(
                    instance,
                    [pattern],
                    table_options,
                    partition["starttime"],
                    partition["endtime"],
                )

        # ------------------------------------------------------------------
        # LakeflowConnect.read_table — single-driver fallback
        # ------------------------------------------------------------------

        def read_table(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Sequential driver-side read.

            Used when the framework falls back from partitioned batch reads, and
            by ``simpleStreamReader`` for any table ``is_partitioned`` excludes.
            """
            self._validate_table(table_name)
            table_options = table_options or {}

            if table_name == "items":
                return self._read_items_snapshot(table_options)
            if table_name == "values":
                return self._read_values_incremental(start_offset, table_options)
            return self._read_timeseries_windowed(start_offset, table_options)

        def _read_items_snapshot(
            self, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Full re-list of the item catalog. Snapshot tables carry no offset."""
            records: list[dict] = []
            patterns = _resolve_item_patterns(table_options)
            for instance in self._resolve_instances(table_options):
                records.extend(self._fetch_items(instance, patterns, table_options))
            return iter(records), {}

        def _read_values_incremental(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Current values changed since the checkpoint.

            The offset is the init-time cap rather than the maximum observed
            ``timestamp``: the endpoint returns one row per item with no ordering
            guarantee and no upper time bound, so there is no reliable
            record-derived cursor to advance to. Re-reading a boundary row on the
            next trigger is harmless because ``values`` upserts on
            ``(instance, item_name)``.
            """
            since = (start_offset or {}).get("cursor")
            if since and since >= self._init_time:
                # Already caught up to this trigger's cap — converge without
                # touching the API.
                return iter([]), start_offset

            max_records = _parse_int(
                table_options.get("max_records_per_batch"),
                DEFAULT_MAX_RECORDS_PER_BATCH,
                minimum=1,
            )
            patterns = _resolve_item_patterns(table_options)

            records: list[dict] = []
            for instance in self._resolve_instances(table_options):
                if len(records) >= max_records:
                    break
                for record in self._fetch_values(instance, patterns, table_options, since):
                    records.append(record)
                    # Client-side truncation is safe here: the table is CDC with
                    # a primary key, so anything cut mid-flight is re-delivered
                    # next trigger and merged.
                    if len(records) >= max_records:
                        break

            return iter(records), {"cursor": self._init_time}

        def _read_timeseries_windowed(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Sliding ``[starttime, endtime)`` walk, one micro-batch per call.

            The cursor advances to the *window boundary*, never to the last
            record's timestamp: an empty window must still move the cursor
            forward or the read would re-scan it forever and never satisfy
            ``end_offset == start_offset``.

            ``max_records_per_batch`` is best-effort by design — a window is
            always drained completely. Truncating inside a window would either
            duplicate or drop rows on an append-only table, since the next call
            would re-request the same instant.
            """
            start_iso, hard_end = self._resolve_timeseries_range(
                table_options, start_offset, None
            )
            if start_iso >= hard_end:
                return iter([]), start_offset if start_offset else {"cursor": hard_end}

            window_seconds = _parse_int(
                table_options.get("window_seconds"), DEFAULT_WINDOW_SECONDS, minimum=1
            )
            max_records = _parse_int(
                table_options.get("max_records_per_batch"),
                DEFAULT_MAX_RECORDS_PER_BATCH,
                minimum=1,
            )
            max_windows = _parse_int(
                table_options.get("max_windows_per_read"),
                DEFAULT_MAX_WINDOWS_PER_READ,
                minimum=1,
            )

            instances = self._resolve_instances(table_options)
            patterns = _resolve_item_patterns(table_options)

            records: list[dict] = []
            cursor = start_iso
            for _ in range(max_windows):
                if cursor >= hard_end:
                    break
                window_end = min(_add_seconds(cursor, window_seconds), hard_end)
                for instance in instances:
                    records.extend(
                        self._fetch_timeseries(
                            instance, patterns, table_options, cursor, window_end
                        )
                    )
                cursor = window_end
                if len(records) >= max_records:
                    break

            end_offset = {"cursor": cursor}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset
            return iter(records), end_offset

        # ------------------------------------------------------------------
        # Endpoint readers
        # ------------------------------------------------------------------

        def _fetch_items(
            self,
            instance: str,
            patterns: Sequence[str],
            table_options: dict[str, str],
        ) -> list[dict]:
            """``GET /hive/{instance}/items`` for one or more wildcard patterns."""
            params: dict[str, Any] = {
                "item": list(patterns),
                "format": RESPONSE_FORMAT,
            }
            attribs = _split_csv(table_options.get("attrib") or table_options.get("attribs"))
            if attribs:
                params["attrib"] = attribs

            payload = self._get_json(f"/hive/{instance}/items", params)
            return _normalize_items(instance, payload)

        def _fetch_values(
            self,
            instance: str,
            patterns: Sequence[str],
            table_options: dict[str, str],
            updated_since: str | None,
        ) -> list[dict]:
            """``GET /hive/{instance}/values`` — current value per item."""
            params: dict[str, Any] = {
                "item": list(patterns),
                "format": RESPONSE_FORMAT,
            }
            if updated_since:
                params["updatedSince"] = updated_since
            quality = _resolve_quality(table_options)
            if quality:
                params["quality"] = quality

            payload = self._get_json(f"/hive/{instance}/values", params)
            return _normalize_values(instance, payload)

        def _fetch_timeseries(
            self,
            instance: str,
            patterns: Sequence[str],
            table_options: dict[str, str],
            start_iso: str,
            end_iso: str,
        ) -> list[dict]:
            """``GET /hive/{instance}/timeseries`` over one window.

            ``starttime``/``endtime`` are both required by the source. The
            connector treats the window as half-open ``[starttime, endtime)``
            (the reading taken in ``apis_api_doc.md``) and makes consecutive
            windows contiguous, so an append-only row cannot land in two
            windows. If live testing shows the server treats ``endtime`` as
            inclusive, boundary rows would duplicate and the windows should be
            shortened by one interval instead.
            """
            params: dict[str, Any] = {
                "item": list(patterns),
                "starttime": start_iso,
                "endtime": end_iso,
                "format": RESPONSE_FORMAT,
            }
            quality = _resolve_quality(table_options)
            if quality:
                params["quality"] = quality

            aggregate = (table_options.get("aggregate") or "").strip()
            if aggregate:
                if aggregate not in AGGREGATE_VALUES:
                    raise ValueError(
                        f"Unsupported 'aggregate' value {aggregate!r}. Must be one of "
                        f"{sorted(AGGREGATE_VALUES)}"
                    )
                params["aggregate"] = aggregate

            interval_raw = table_options.get("interval")
            if interval_raw not in (None, ""):
                interval = _parse_int(interval_raw, MIN_INTERVAL_SECONDS, minimum=1)
                if not MIN_INTERVAL_SECONDS <= interval <= MAX_INTERVAL_SECONDS:
                    raise ValueError(
                        f"'interval' must be between {MIN_INTERVAL_SECONDS} and "
                        f"{MAX_INTERVAL_SECONDS} seconds, got {interval}"
                    )
                params["interval"] = interval

            payload = self._get_json(f"/hive/{instance}/timeseries", params)
            return _normalize_timeseries(instance, payload)

        # ------------------------------------------------------------------
        # Instance resolution
        # ------------------------------------------------------------------

        def _resolve_instances(self, table_options: dict[str, str]) -> list[str]:
            """Resolve the ``{instance}`` path parameter(s).

            Precedence: table options, then connection options, then a one-time
            ``GET /hive`` lookup. ``/hive`` is a config-time lookup, not a
            table — it produces no rows, only the names every other call needs.
            """
            from_table = _split_csv(
                (table_options or {}).get("instance") or (table_options or {}).get("instances")
            )
            if from_table:
                return from_table
            if self._configured_instances:
                return list(self._configured_instances)
            if self._discovered_instances is None:
                self._discovered_instances = self._discover_instances()
            return list(self._discovered_instances)

        def _discover_instances(self) -> list[str]:
            """``GET /hive`` — the only way to learn instance names.

            The response has no declared schema. Both plausible renderings are
            accepted: a bare array of strings (``["ApisHive"]``) and an array of
            objects carrying a name-ish field.
            """
            payload = self._get_json("/hive", {"format": RESPONSE_FORMAT})
            names: list[str] = []
            for entry in _as_list(payload):
                name = None
                if isinstance(entry, str):
                    name = entry
                elif isinstance(entry, dict):
                    name = _first_str(entry, _INSTANCE_NAME_KEYS)
                if name and name not in names:
                    names.append(name)

            if not names:
                raise RuntimeError(
                    "GET /hive returned no Hive instances. Set the 'instance' "
                    "connection or table option to target one explicitly."
                )
            return names

        # ------------------------------------------------------------------
        # Range / window arithmetic
        # ------------------------------------------------------------------

        def _resolve_timeseries_range(
            self,
            table_options: dict[str, str],
            start_offset: dict | None,
            end_offset: dict | None,
        ) -> tuple[str, str]:
            """Resolve the ``[start, end)`` range for a ``timeseries`` read.

            ``starttime`` is mandatory upstream, and the source offers no way to
            discover the oldest recorded point (no "first value" endpoint), so
            auto-discovery is impossible. The lower bound comes from, in order:
            the committed cursor, an explicit ``start_timestamp``, or
            ``backfill_days`` before the init-time cap.
            """
            end_iso = (end_offset or {}).get("cursor") or self._init_time
            # Never read past this trigger's cap, whatever the caller passed.
            if end_iso > self._init_time:
                end_iso = self._init_time

            start_iso = (start_offset or {}).get("cursor")
            if not start_iso:
                start_iso = (table_options.get("start_timestamp") or "").strip() or None
            if start_iso:
                return _normalize_timestamp(start_iso), end_iso

            backfill_days = _parse_int(
                table_options.get("backfill_days"), DEFAULT_BACKFILL_DAYS, minimum=1
            )
            return _add_seconds(end_iso, -backfill_days * 86_400), end_iso

        def _build_windows(
            self,
            start_iso: str,
            end_iso: str,
            table_options: dict[str, str],
            slices: int,
        ) -> list[tuple[str, str]]:
            """Chop ``[start, end)`` into contiguous, non-overlapping windows.

            ``max_partitions`` bounds the task count: when the requested range
            needs more windows than the budget allows, the window is widened
            rather than emitting thousands of tiny tasks. ``slices`` is the
            number of (instance x pattern) combinations each window is
            multiplied by, so the budget accounts for the full fan-out.
            """
            window_seconds = _parse_int(
                table_options.get("window_seconds"), DEFAULT_WINDOW_SECONDS, minimum=1
            )
            max_partitions = _parse_int(
                table_options.get("max_partitions"), DEFAULT_MAX_PARTITIONS, minimum=1
            )

            total_seconds = max(1, int((_parse_iso(end_iso) - _parse_iso(start_iso)).total_seconds()))
            window_budget = max(1, max_partitions // max(1, slices))
            needed = math.ceil(total_seconds / window_seconds)
            if needed > window_budget:
                window_seconds = math.ceil(total_seconds / window_budget)

            windows: list[tuple[str, str]] = []
            cursor = start_iso
            while cursor < end_iso:
                window_end = min(_add_seconds(cursor, window_seconds), end_iso)
                windows.append((cursor, window_end))
                cursor = window_end
            return windows

        # ------------------------------------------------------------------
        # HTTP layer
        # ------------------------------------------------------------------

        def _headers(self) -> dict[str, str]:
            value = f"{self._auth_scheme} {self._token}".strip() if self._auth_scheme else self._token
            return {"Authorization": value, "Accept": "application/json"}

        def _get_json(self, path: str, params: dict[str, Any]) -> Any:
            """Issue one GET and return the parsed JSON body.

            Deliberately single-shot: the source documents no pagination, so
            there is no next-page parameter to follow. A ``206 Partial Content``
            means the server truncated the result and there is *no* documented
            way to resume — the only mitigation the spec allows is a narrower
            ``item`` pattern or a shorter window, so we surface a warning rather
            than silently returning a partial table.
            """
            url = f"{self._base_url}{path}"
            response = self._request_with_retry(url, params)

            if response.status_code == 206:
                logger.warning(
                    "Apis %s returned 206 Partial Content: the server truncated the "
                    "result and the API defines no continuation token, Link header or "
                    "offset parameter to resume with. Narrow the 'item' pattern "
                    "(e.g. per-module wildcards) or shorten 'window_seconds' to keep "
                    "responses whole.",
                    path,
                )
            elif response.status_code != 200:
                raise RuntimeError(
                    f"Apis request failed: GET {path} -> HTTP {response.status_code}: "
                    f"{response.text[:500]}"
                )

            if not response.content:
                return []
            try:
                return response.json()
            except ValueError as exc:
                raise RuntimeError(
                    f"Apis request GET {path} returned a non-JSON body: "
                    f"{response.text[:500]}"
                ) from exc

        def _request_with_retry(self, url: str, params: dict[str, Any]) -> requests.Response:
            """GET with exponential backoff on transient failures.

            The spec documents no rate limits and declares no ``429`` anywhere,
            so the retry set is the conservative union of throttling and gateway
            codes rather than anything the source promised.
            """
            backoff = INITIAL_BACKOFF_SECONDS
            last_error: Exception | None = None
            response: requests.Response | None = None

            for attempt in range(self._max_retries):
                try:
                    response = self._session.get(
                        url,
                        params=params,
                        headers=self._headers(),
                        timeout=self._timeout,
                        verify=self._verify_ssl,
                    )
                    if response.status_code not in RETRIABLE_STATUS_CODES:
                        return response
                    last_error = None
                except (requests.Timeout, requests.ConnectionError) as exc:
                    last_error = exc
                    response = None

                if attempt < self._max_retries - 1:
                    time.sleep(backoff)
                    backoff *= 2

            if response is not None:
                return response
            raise RuntimeError(
                f"Apis request failed after {self._max_retries} attempts: {url}"
            ) from last_error

        # ------------------------------------------------------------------
        # Misc
        # ------------------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Table {table_name!r} is not supported. Supported tables: "
                    f"{list(SUPPORTED_TABLES)}"
                )


    # ---------------------------------------------------------------------------
    # Response normalizers
    #
    # Only ``values`` has a spec-declared body. The other two parsers accept
    # several plausible renderings on purpose: guessing one shape and hard-failing
    # on the rest would make the connector brittle against the very uncertainty
    # the spec leaves open. Each branch below is labelled with why it is plausible.
    # ---------------------------------------------------------------------------


    def _normalize_items(instance: str, payload: Any) -> list[dict]:
        """Project an ``items`` response onto ``ITEMS_SCHEMA``.

        Accepted renderings for the identifying field (CONFIRMED live: the real
        server sends ``name``, not the spec's ``item_name``):
          * array of objects with an item-name field (``item_name`` per
            ``single_value_t``, or ``name``/``item``);
          * array of bare item-name strings;
          * object keyed by item name, value = attribute bag.
        """
        records: list[dict] = []
        for name, entry in _iter_named_entries(payload, _ITEM_NAME_KEYS):
            if not name:
                continue
            records.append(
                {
                    "instance": instance,
                    "item_name": name,
                    # CONFIRMED live: matches the real `modules` endpoint's
                    # module names exactly, including for deeply nested paths.
                    "module": name.split(".", 1)[0] if "." in name else None,
                    # CONFIRMED live: the source's own field is named "type"
                    # (observed: "Signal", "Function item", "Status").
                    "item_type": entry.get("type") if isinstance(entry, dict) else None,
                    "attributes": _normalize_attributes(entry),
                }
            )
        return records


    def _normalize_attributes(entry: Any) -> list[dict] | None:
        """Best-effort projection of the ``attrib`` payload.

        The spec says only that ``attrib`` takes numeric "Attribute ID" values;
        it never says how they come back, and there is no ID-to-meaning registry
        anywhere in the document. Both a list form and a mapping form are
        accepted, and anything unrecognised yields ``None`` rather than a guess.
        """
        if not isinstance(entry, dict):
            return None

        raw = entry.get("attributes")
        if raw is None:
            raw = entry.get("attribs")

        if isinstance(raw, list):
            out: list[dict] = []
            for item in raw:
                if isinstance(item, dict):
                    attrib_id = _first_str(item, ("attrib_id", "attrib", "id", "attribute_id"))
                    out.append(
                        {
                            "attrib_id": attrib_id,
                            "value": _as_str(
                                item.get("value") if "value" in item else item.get("v")
                            ),
                        }
                    )
                else:
                    out.append({"attrib_id": None, "value": _as_str(item)})
            return out

        if isinstance(raw, dict):
            return [
                {"attrib_id": str(key), "value": _as_str(value)}
                for key, value in raw.items()
            ]

        # Fall back to numerically-named top-level keys — the shape a server
        # would produce if it inlined requested attribute IDs onto the item.
        inline = [
            {"attrib_id": str(key), "value": _as_str(value)}
            for key, value in entry.items()
            if str(key).isdigit()
        ]
        return inline or None


    def _normalize_values(instance: str, payload: Any) -> list[dict]:
        """Project a ``values`` response onto ``VALUES_SCHEMA``.

        SPEC-DECLARED shape: ``[{"item_name": ..., "value": {"v","q","t"}}]``.
        A flattened ``{"item_name","v","q","t"}`` rendering is also tolerated,
        since the declared schema is the *only* one in the document and a thin
        service could easily inline the triple. Either way, the wire triple is
        flattened onto the row's ``value``/``quality``/``timestamp`` columns.
        """
        records: list[dict] = []
        for name, entry in _iter_named_entries(payload, _ITEM_NAME_KEYS):
            records.append(
                {
                    "instance": instance,
                    "item_name": name,
                    **_flatten_point(_extract_point(entry)),
                }
            )
        return records


    def _normalize_timeseries(instance: str, payload: Any) -> list[dict]:
        """Project a ``timeseries`` response onto ``TIMESERIES_SCHEMA``.

        INFERRED shape — the single largest gap in the source spec (neither
        ``200`` nor ``206`` declares any ``content``). One row is emitted per
        (item, point in time). Accepted renderings, all structurally derived
        from ``single_value_t``:

          * per-item bundle: ``[{"item_name": X, "values": [{v,q,t}, ...]}]``
            — the shape implied by ``aggregate``/``interval`` being per-item,
            per-bucket concepts;
          * per-item single point: ``[{"item_name": X, "value": {v,q,t}}]``
            — i.e. ``values``' declared shape reused verbatim;
          * flat point stream: ``[{"item_name": X, "v":..., "q":..., "t":...}]``.
        """
        records: list[dict] = []
        for name, entry in _iter_named_entries(payload, _ITEM_NAME_KEYS):
            for point in _extract_points(entry):
                records.append(
                    {
                        "instance": instance,
                        "item_name": name,
                        **_flatten_point(point),
                    }
                )
        return records


    def _extract_points(entry: Any) -> list[dict | None]:
        """Pull every ``(v, q, t)`` point out of one per-item entry."""
        if not isinstance(entry, dict):
            return [_extract_point(entry)]

        for key in ("values", "value", "points", "data"):
            raw = entry.get(key)
            if isinstance(raw, list):
                return [_extract_point(point) for point in raw]
            if isinstance(raw, dict):
                return [_extract_point(raw)]

        if any(key in entry for key in _POINT_KEYS):
            return [_extract_point(entry)]
        return []


    def _extract_point(raw: Any) -> dict | None:
        """Coerce one point into a ``{"v", "q", "t"}`` dict.

        Returns ``None`` rather than ``{}`` when nothing usable is present —
        ``_flatten_point`` maps that into all-``None`` output columns.
        """
        if isinstance(raw, dict):
            nested = raw.get("value")
            if isinstance(nested, dict):
                raw = nested
            if not any(key in raw for key in _POINT_KEYS):
                return None
            return {"v": raw.get("v"), "q": raw.get("q"), "t": raw.get("t")}
        if raw is None:
            return None
        # A bare scalar: the value itself, with no quality or timestamp.
        return {"v": raw, "q": None, "t": None}


    def _flatten_point(point: dict | None) -> dict:
        """Project a ``{"v", "q", "t"}`` point onto flat ``value``/``quality``/
        ``timestamp`` row columns (``VALUES_SCHEMA``/``TIMESERIES_SCHEMA``),
        rather than keeping the wire shape nested, so downstream SQL can
        reference each field directly without a struct accessor.
        """
        point = point or {}
        return {
            "value": point.get("v"),
            "quality": point.get("q"),
            "timestamp": point.get("t"),
        }


    def _iter_named_entries(
        payload: Any, name_keys: Sequence[str]
    ) -> Iterator[tuple[str | None, Any]]:
        """Yield ``(item_name, entry)`` pairs from any of the plausible shapes."""
        if isinstance(payload, dict):
            # Either a wrapper around the array, or a mapping keyed by item name.
            for key in ("items", "values", "results", "data", "value"):
                inner = payload.get(key)
                if isinstance(inner, list):
                    yield from _iter_named_entries(inner, name_keys)
                    return
            for key, value in payload.items():
                if isinstance(value, (dict, list)) or not str(key).isdigit():
                    yield str(key), value
            return

        for entry in _as_list(payload):
            if isinstance(entry, str):
                yield entry, None
            elif isinstance(entry, dict):
                yield _first_str(entry, name_keys), entry


    def _as_list(payload: Any) -> list:
        if payload is None:
            return []
        if isinstance(payload, list):
            return payload
        return [payload]


    # ---------------------------------------------------------------------------
    # Small helpers
    # ---------------------------------------------------------------------------


    def _resolve_quality(table_options: dict[str, str]) -> str | None:
        quality = (table_options.get("quality") or "").strip().lower()
        if not quality:
            return None
        if quality not in QUALITY_VALUES:
            raise ValueError(
                f"Unsupported 'quality' value {quality!r}. Must be one of "
                f"{sorted(QUALITY_VALUES)}"
            )
        return quality


    def _resolve_item_patterns(table_options: dict[str, str]) -> list[str]:
        """``item`` is a required query parameter, so there is always a pattern."""
        raw = (
            (table_options or {}).get("item")
            or (table_options or {}).get("items")
            or (table_options or {}).get("item_patterns")
        )
        patterns = _split_csv(raw)
        return patterns or [DEFAULT_ITEM_PATTERN]


    def _split_csv(raw: Any) -> list[str]:
        if raw is None:
            return []
        if isinstance(raw, (list, tuple)):
            values = [str(v).strip() for v in raw]
        else:
            values = [part.strip() for part in str(raw).split(",")]
        out: list[str] = []
        for value in values:
            if value and value not in out:
                out.append(value)
        return out


    def _first_str(entry: dict, keys: Sequence[str]) -> str | None:
        for key in keys:
            value = entry.get(key)
            if isinstance(value, str) and value:
                return value
            if isinstance(value, (int, float)):
                return str(value)
        return None


    def _as_str(value: Any) -> str | None:
        if value is None:
            return None
        if isinstance(value, str):
            return value
        return str(value)


    def _parse_int(value: Any, default: int, *, minimum: int = 0) -> int:
        try:
            parsed = int(str(value).strip())
        except (TypeError, ValueError, AttributeError):
            return default
        return parsed if parsed >= minimum else default


    def _parse_iso(value: str) -> datetime:
        normalised = str(value).strip().replace("Z", "+00:00")
        try:
            parsed = datetime.fromisoformat(normalised)
        except ValueError as exc:
            raise ValueError(
                f"Invalid ISO-8601 timestamp {value!r}. The source also accepts "
                f"relative 'OPC time' expressions (e.g. 'DAY-1D'), but this "
                f"connector always sends absolute instants so incremental reads "
                f"stay deterministic — supply an absolute timestamp."
            ) from exc
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=timezone.utc)
        return parsed.astimezone(timezone.utc)


    def _format_iso(value: datetime) -> str:
        return value.astimezone(timezone.utc).strftime(TIMESTAMP_FORMAT)


    def _normalize_timestamp(value: str) -> str:
        return _format_iso(_parse_iso(value))


    def _add_seconds(iso_value: str, seconds: int) -> str:
        shifted = _parse_iso(iso_value) + timedelta(seconds=seconds)
        epoch = _parse_iso(EPOCH_ISO)
        if shifted < epoch:
            shifted = epoch
        return _format_iso(shifted)


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = ApisLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
